WebEncantadas/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebEncantadas.Data;
using WebEncantadas.Models.ViewModels;

namespace WebEncantadas.Controllers
{
    public class CadastroController : Controller
    {
        private readonly Contexto _context;

        public CadastroController(Contexto context)
        {
            _context = context;
        }


        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create_([Bind("id, NomeResponsavel,CPF,Email,ConfirmacaoEmail,Contato,ContatoEmergencial,NomeCrianca_1,IdadeCrianca_1,DataDeNascimento_1,RestricaoAlimentar_1,NomeCrianca_2,IdadeCrianca_2,DataDeNascimento_2,RestricaoAlimentar_2,NomeCrianca_3,IdadeCrianca_3,DataDeNascimento_3,RestricaoAlimentar_3,NomeCrianca_4,IdadeCrianca_4,DataDeNascimento_4,RestricaoAlimentar_4, Senha")] CadastroViewModel cadastro)
        {
            // retorno da View precisa ser revisto
            if (ModelState.IsValid)
            {
               
                _context.Add(cadastro);
                await _context.SaveChangesAsync();

                return RedirectToAction("Login");
            }
            return View(cadastro);
        }
    }
}

WebEncantadas/Controllers/ChaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebEncantadas.Controllers
{
    public class ChaController : Controller
    {

        public IActionResult Cha()
        {
            return View();
        }

     
    }
}

WebEncantadas/Controllers/DuvidasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebEncantadas.Controllers
{
    public class DuvidasController : Controller
    {

        public IActionResult Duvidas()
        {
            return View();
        }

     
    }
}

WebEncantadas/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebEncantadas.Data;
using WebEncantadas.Helper;
using WebEncantadas.Models.Contracts.Services;
using WebEncantadas.Models.Entities;
using WebEncantadas.Models.ViewModels;

namespace WebEncantadas.Controllers
{
    public class LoginController : Controller
    {
        private readonly Contexto _context;
        private readonly ISessao _sessao;
        private readonly ConnectionManager _connection = new ConnectionManager();
        private readonly IUsuarioService _usuarioService;

        public LoginController(ISessao sessao, IUsuarioService usuarioService, Contexto contexto)
        {
            _sessao = sessao;
            _usuarioService = usuarioService;
            _context = contexto;
        }
        public IActionResult Login()
        {
            //se usuário estiver logado, redirecionar para a home
            if(_sessao.BuscarSessaoUsuario() != null)
            {
                ViewBag.UsuarioLogado = true;
                return RedirectToAction("Index", "Home");
            }
            ViewBag.UsuarioLogado = false;
            return View();
        }

        public IActionResult SairSessaoUsuario()
        {
            _sessao.RemoverSessaoUsuario();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logar(string login, string senha)
        {
            try
            {
                // retorno da View precisa ser revisto
                if (ModelState.IsValid)
                {
                    bool usuarioValido = await _usuarioService.ValidarUsuario(login, senha);
                    if (usuarioValido)
                    {
                        Usuario usuario = new Usuario();
                        usuario.Login = login;
                        usuario.Senha = senha;
                        _sessao.CriarSessaoUsuario(usuario);
                        TempData["usuarioLogado"] = usuario.Login;
                        TempData["login"] = usuario.Login;
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["MensagemErro"] = $"Login inválido";
                    }

                    //var query =  SqlManager.GetSql(Models.TSql.EFETUAR_LOGIN);

                }
                return View("Index");

    }
            catch (System.Exception)
            {

                throw;
            };
        }
    }
}

WebEncantadas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebEncantadas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
</head>

<style>
    .linkColor {
        color: #ffffffed !important;
    }

    /*.fundoGeralHome {
        background-image: url('./CAM_3527.jpg'); 
        background-size: cover; /* Para cobrir todo o elemento */
        /*background-position: center; 
        background-color: rgba(0, 0, 0, 4); /* Cor preta com 50% de opacidade */
    

</style>
<body class="fundoGeralHome">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 minhaNavBar">
            <div class="container">

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 linksCabecalho">
                        @{
                            if (TempData["usuarioLogado"] != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Home" asp-action="Index">Olá, @TempData["login"]</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Home" asp-action="Index">Olá</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            @*Ingresso é o nome da minha controller e Reserve é a função chamada da controller*@
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Ingresso" asp-action="Reserve">Compre seu ingresso</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Quem_Somos" asp-action="Quem_Somos">Quem Somos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Cha" asp-action="Cha">Funcionamento do Chá</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="FotosVideos" asp-action="FotosVideos">Fotos e Vídeos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Cadastro" asp-action="Create">Cadastre-se</a>
                        </li>
                        @{
                            if (TempData["usuarioLogado"] != null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Login" asp-action="SairSessaoUsuario">Sair</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Login" asp-action="Login">Logar</a>
                                </li>
                            }
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark linkColor" asp-area="" asp-controller="Duvidas" asp-action="Duvidas">Dúvidas Frequentes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*ESSA FUNÇÃO FAZ AS CHAMADAS PARA AS MINHAS PÁGINAS*@
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebEncantadas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>