WebEncantadas/Controllers/IngressoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebEncantadas.Business.ServiceReserva.Abstracts;
using WebEncantadas.Data;
using WebEncantadas.Data.ReservaIngresso.Abstractions;
using WebEncantadas.Helper;
using WebEncantadas.Models.Contracts.Services;
using WebEncantadas.Models.Entities;

namespace WebEncantadas.Controllers
{
    public class IngressoController : Controller
    {
        // GET: IngressoController
        private readonly IReservaService _reservaService;

        public IngressoController(IReservaService reservaService)
        {
            _reservaService = reservaService;
        }

        public async Task<IActionResult> Reserve()
        {
            Mesas mesas = await _reservaService.BuscarEconstruirMesas();

            return View(mesas);
        }

        //// GET: IngressoController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: IngressoController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: IngressoController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: IngressoController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: IngressoController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: IngressoController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: IngressoController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

WebEncantadas/Controllers/PagamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebEncantadas.Controllers
{
    public class PagamentoController : Controller
    {
        public double valorIngresso { get; set; }



        //[HttpPost]
        //public JsonResult AtualizaPagamento()
        //{
        //    double valorIngresso = 200.00;
        //    return Json(new
        //    {
        //        ValorIngresso = valorIngresso
        //    });
        //}

        public IActionResult Index()
        {
            double valorIngresso = 200.00;
            var valorIngresso_json = JsonConvert.SerializeObject(valorIngresso);
            return Json(valorIngresso_json);
        }

        public IActionResult CalcularValorTotal(int numero_deCadeiras)
        {
            double valorPorCadeira = 200.00;
            double valorToal = numero_deCadeiras * valorPorCadeira;
            var valorToal_json = JsonConvert.SerializeObject(valorToal);  
            return Json(valorToal_json);
        }
    }
}

WebEncantadas/Views/Ingresso/Reserve.cshtml
@using WebEncantadas;
@using System.Configuration;
@using System.Data.SqlClient;
@using WebEncantadas.Models.Entities
@model Mesas

@{
    ViewData["Title"] = "Ingresso";
}


<head>
    <link rel="stylesheet" href="~/css/style_Reserve.css" />
</head>

<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>

<h1>Reserva de ingressos</h1>

<div class="salaoMesas">

    <div class="divisao_1">
        <div id="mesa_circular">
            @for (int i = 1; i <= 8; i++)
            {
                // caso esteja já reservado, meu botão fica desabilitado
                if (@Model.Mesa1[i - 1].cadeira_reservada == 1)
                {
                    <button id="cadeira-@i" disabled class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="1">@i</button>
                }
                else
                {
                    <button id="cadeira-@i" class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="1">@i</button>
                }
            }
        </div>

        <div id="mesa_circular2">
            @for (int i = 1; i <= 8; i++)
            {
                if (@Model.Mesa2[i -1].cadeira_reservada == 1)
                {
                         <button id="cadeira-@i"  disabled class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="2">@i</button>
                }
                else
                {
                         <button id="cadeira-@i" class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="2">@i</button>
                }
           
            }
        </div>
    </div>

    <div class="divisao_2">
        <div id="mesa_circular3">
            @for (int i = 1; i <= 8; i++)
            {
                if (@Model.Mesa3[i -1].cadeira_reservada == 1)
                {
                       <button id="cadeira-@i" disabled class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="3">@i</button>
                }
                else
                {
                       <button id="cadeira-@i" class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="3">@i</button>
                }
             
            }
        </div>

        <div id="mesa_circular4">
            @for (int i = 1; i <= 8; i++)
            {
                if (@Model.Mesa4[i -1].cadeira_reservada == 1)
                {
                      <button id="cadeira-@i" disabled class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="4">@i</button>
                }
                else
                {
                      <button id="cadeira-@i" class="assento-@i cadeira" onclick="cadeiraSelecionada(this)" data-num-mesa="4">@i</button>
                }
              
            }
        </div>
    </div>

    <div>
        <div>
            Valor total:
            <span id="totalCompra"></span>


        </div>
    </div>
</div>

<p>O valor da mesa é @Model.Mesa1[0].valor_cadeira</p>


<script>


    function cadeiraSelecionada(botao) {
         botao.classList.toggle("selecionada"); // faz com que adicione class "selecionada" caso a mesma não exista. Caso clicar no botão de novo e a class "selecionada" existir, eu removo ela.
          atualizarValorTotal();
    }

    function atualizarValorTotal() {
         var numero_deCadeiras = $('.cadeira.selecionada').length; // obtém o número de cadeiras selecionadas
         $.ajax({
             url: '@Url.Action("CalcularValorTotal", "Pagamento")',
             data: { numero_deCadeiras: numero_deCadeiras },
             success: function (data) {
                 $('#totalCompra').html('R$ ' + data); // atualiza o valor total na tela
             }
         });
     }

     $(function () {
         atualizarValorTotal(); // atualiza o valor total na página carregada
     });

</script>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}